### ISSUE TITLE
CSV fields got turned into numeric

### ISSUE THREAD

**Issue by nkrishnaswami** [CT-Data-Collaborative/2022-tract-crosswalk#1]
Hi, when I look at the raw CSV [2022tractcrosswalk.csv](https://raw.githubusercontent.com/CT-Data-Collaborative/2022-tract-crosswalk/refs/heads/main/2022tractcrosswalk.csv), I see that the leading zeroes are gone for it looks like everything.

**Comment by jillctdata** [comment]
Thank you for raising this! It is fixed now.
