### ISSUE TITLE
How was this crosswalk produced?

### ISSUE THREAD

**Issue by raphaellaude** [CT-Data-Collaborative/2022-tract-crosswalk#2]
Hi there! Thank you for putting this together. If possible, I'd love to hear a little more about how this crosswalk was put together. Adding the script used to produce the table–if a script was used–to the repo would be super helpful. :)

**Comment by jillctdata** [comment]
Hi,

We used QGIS to create the crosswalk, happy to chat more over email (info@ctdata.org).

Thanks!
